src/ui/mod.rs
Just fixes some typos in your user interface. Thanks for the great work!
=> Fixes typos

README.md
Cleaned up the instructions in the readme.
Also fixed a few typos and added an emoji for fun 🎉
=> Updated the instructions in the readme

src/ui/mod.rs
There are a few issues being raised due to poor error messages when trying to play tracks.
This tries to clarify what to check when playing a track doesn't work, but more could be done such as fetching the user and checking their subscription type to ensure they have a premium memebership.
=> Improve error message

CHANGELOG.md, src/main.rs
Not sure how to test this change, advice appreciated
=> Get a new token when the token expires

README.md, src/app.rs, src/main.rs
- Use 'n' to go to the next track, and use 'p' to go to the previous track
- Updated the README to show progress
=> Add next and previous track functionality

CHANGELOG.md, README.md, src/app.rs, src/main.rs, src/ui/help.rs
You can now use `<` to seek backwards 5 seconds and `>` to go forwards 5
seconds
=> Implement seek functionality

CHANGELOG.md, src/handlers/mod.rs, src/main.rs, src/ui/help.rs
The event `A` will jump to the album list of the first artist in the
track's artists list
=> Jump to currently playing artist's album list

CHANGELOG.md, src/app.rs, src/handlers/mod.rs, src/main.rs, src/ui/help.rs, src/ui/mod.rs
Use `-` to decrease and `+` to increase volume in 10% increments.
Thanks to @jfaltis for the bindings suggestion.
Closes https://github.com/Rigellute/spotify-tui/issues/57
=> Implement volume control

src/app.rs, src/handlers/input.rs, src/ui/mod.rs
This may make it easier to handle inputs since we do not have to care
about character boundaries in Strings.
See #30
I'm not sure whether this is a good idea performance-wise, I would like
to hear your opinions
=> RFC: Use Vec<char> for input instead of String

src/app.rs
=> Fix app crash when pressing `q` then `down`

src/main.rs
Addresses https://github.com/Rigellute/spotify-tui/issues/3
=> Add collaborative playlists to `Playlists` view

src/handlers/album_list.rs, src/handlers/album_tracks.rs, src/handlers/artist_albums.rs, src/handlers/artists.rs, src/handlers/common_key_events.rs, src/handlers/empty.rs, src/handlers/error_screen.rs, src/handlers/help_menu.rs
Use `crate::` instead of `super::super::`
=> Minor stylistic change to import path

src/app.rs, src/config.rs, src/handlers/home.rs, src/handlers/library.rs, src/handlers/made_for_you.rs, src/handlers/playbar.rs, src/handlers/playlist.rs, src/handlers/podcasts.rs, src/handlers/recently_played.rs, src/handlers/search_results.rs, src/handlers/select_device.rs, src/handlers/track_table.rs, src/main.rs, src/redirect_uri.rs, src/ui/mod.rs, src/user_config.rs, src/util.rs
Ran rustfmt merge imports. 
I really like this in my libraries. To me, this looks way cleaner.
=> Merge imports

src/config.rs, src/main.rs, src/redirect_uri.rs
Possible to change the port for the webserver.
Issue: https://github.com/Rigellute/spotify-tui/issues/187
=> add possibility to change port

README.md, src/app.rs, src/handlers/mod.rs, src/ui/help.rs, src/user_config.rs
In conjunction with issue #223 
Let me know if further changes need to be made, or if anything doesn't work as intended.
=> Added copy_album_url functionality

README.md, src/app.rs, src/handlers/mod.rs, src/ui/help.rs, src/user_config.rs
Original PR here https://github.com/Rigellute/spotify-tui/pull/224
Thanks to @calenrobinette
This PR just fixes the clippy warning of cognitive complexity.
=> @calenrobinette - Added copy_album_url functionality

src/main.rs
=> Fix tiny term crash

src/app.rs, src/handlers/album_tracks.rs, src/handlers/input.rs, src/ui/mod.rs
Original PR #280 thanks to @AlexandreSi
=> Search album by url

README.md, src/main.rs, src/ui/mod.rs, src/ui/util.rs, src/user_config.rs
=> Add user theme configuration

README.md, src/app.rs, src/user_config.rs
Hey,
I added a way to change the volume increment in `config.yml`
Thanks for your work so far, let me know if you need anything else
=> Add option to change volume increment

.github/workflows/snap.yml, snap/snapcraft.yaml
Please add secrets to repo before accepting pull request. See email. If you have any question please fee free to contact me via email.
=> Enable github workflow for snaps.

README.md, src/handlers/mod.rs, src/main.rs, src/ui/audio_analysis.rs, src/ui/mod.rs, src/ui/util.rs, src/user_config.rs
This PR includes a few more adjustments for the new audio visualiser.
=> Visualiser refinement

src/handlers/mod.rs
=> Remove escape event from device and analysis views

src/handlers/search_results.rs, src/ui/mod.rs
This commit also shows the saved status of tracks in the list.
In addition, tracks played within this list will go continue to play
through the list -> pressing "next" or "previous" will use this list.
Closes #334
=> Show currently playing track in song search menu

src/ui/mod.rs
=> Show currently playing top track

src/handlers/input.rs
=> Prevent search when there is no input

src/app.rs, src/handlers/artist.rs, src/network.rs
=> Refactoring

src/app.rs, src/handlers/library.rs, src/network.rs
re: #332
Fix async navigation in a couple places:
* Analysis
* Liked Songs
* Recently Played
=> Fix async navigation in a couple places

src/ui/mod.rs
=> Add artist name in songs block

Cargo.lock
Rengenerated using `cargo generate-lockfile`
Closes #375
=> Regenerate lock file

src/main.rs, src/user_config.rs
Closes Rigellute/spotify-tui#355
=> Allow specifying alternative config file path

src/ui/mod.rs
Simple feature.
Closes Rigellute/spotify-tui#387
=> List artists names in the album view

src/network.rs
=> Fix unwrap crash when opening playlist

.gitignore, src/app.rs, src/handlers/dialog.rs, src/handlers/mod.rs, src/handlers/playlist.rs, src/handlers/search_results.rs, src/ui/clear.rs, src/ui/mod.rs
Added some support for future confirmation dialogs, also.
Closes #384
=> Confirm delete

src/app.rs, src/handlers/artist.rs, src/handlers/search_results.rs, src/ui/mod.rs
Currently, album save and artist follow are enabled in search result only.
In this PR, I added support for album save/delete and artist follow/unfollow in artist view.
=> Add support for saving an album and following an artist in artist view

src/ui/mod.rs
Since we're already using the Geometric block for the heart, it just made sense to use something a little more elegant for the current indicator. :) Let me know if this causes any issues.
=> Change currently_playing indicator

src/handlers/basic_view.rs
Add the feature to like a song with the 's' key when you are in the basic view.
closes #478 
Any comments or suggestions are welcome.
=> Add feature to like a song from basic view

src/ui/mod.rs
In order to solve [#538 ](https://github.com/Rigellute/spotify-tui/issues/538)
=> Show ♥ next to album name in saved list

rustfmt.toml, src/app.rs, src/network.rs, src/ui/help.rs
Small-ish PR to get basic podcast support kickstarted. I plan on adding more support for searching and following podcasts, but figured I'd tackle the low hanging fruit first.
Things added:
* playback progress bar
* seek forward/backward
* copy episode/show uri
=> Add basic playbar support for podcasts

src/app.rs
This PR is fix of PR #445 
I have checked that can follow/unfollow an artist in the search result view.
=> Fix to be able to follow an artist in search result view

src/handlers/album_tracks.rs, src/handlers/artist.rs, src/handlers/recently_played.rs, src/handlers/search_results.rs, src/handlers/track_table.rs, src/network.rs, src/ui/help.rs, src/user_config.rs
Using the new method in rspotify, we can now queue a song.
I have set the deafult to 'z', but it should probably be changed before the code
is merged.
This is in reference to issue #304 
Please let me know if there are better ways to do this, then I can improve the
code
=> Add possibility to queue a song

.github/workflows/ci.yml, src/handlers/common_key_events.rs
The latest rust upgrade brought some new warnings from clippy. This PR fixes them.
=> Fix new clippy warnings

src/handlers/made_for_you.rs
=> Fix app crash due to unwrap

.github/workflows/ci.yml
=> ci - clippy: upgrade toolchain

.github/workflows/cd.yml
Extracting variables like that works for me [here](https://github.com/rust-github/rust-gh-example/blob/01e0aae91f83e1e932f4498a0eddb2905c8fffc3/.github/workflows/cd.yml#L74-L95).
=> cd: extract variables in order to simplify script

src/app.rs
I often use Daily Drive, so I added it to the other Made For You entries in `app.rs`.
=> app: add Daily Drive to Made For You lists search.

Cargo.lock, Cargo.toml, src/ui/mod.rs
=> Update tui lib to 0.14.0

Cargo.lock, Cargo.toml, src/cli/cli_app.rs, src/handlers/track_table.rs
=> updated rand crate

Cargo.lock, Cargo.toml, src/main.rs
=> crossterm updated

README.md
Close #726
Implementations:
- Minor update in README.md
=> docs(README): fix default shortcut for shuffle config

README.md
Added description of client.yml file path when using snap.
=> docs: client.yml file path in snap
