- CHANGELOG.md
- README.md
- src/app.rs
- src/handlers/input.rs
- src/main.rs
- src/ui/help.rs
- src/ui/mod.rs
Included a keybind for repeat modes, which cycles through Off -> All -> Track -> Off as in the Electron client. Interface has a small visual update to show the repeat status next to the shuffle status, seen [here](https://i.imgur.com/MYKgbRN.png). The keybind inherits from shuffle (both ctrl+first letter) which seems consistent to me, but feel free to change it if you see fit.
Also closes #17, which was caused by the client not choosing between different versions of the same album available to disjoint sets of countries. It's not a permanent fix though, as it just follows the example set in `input.rs` by always requesting the UK versions. It is a little more future-proof in that both now make requests according to a new `App::country` field, but it's still essentially hard-coded. New …
> Add Ctrl-r to cycle repeat mode; fix duplicate albums

- src/ui/mod.rs
Currently when a playing track is selected it loses it's format ("|>" prefix) and style.
Before
Fixed
> Keep format of highligted track when it is playing

- README.md
For building this project, OpenSSL needs to be installed.
In order for the OpenSSL installation to be automatically found, ```pkg-config``` is needed on Linux, ```homebrew``` on macOS and ```vcpkg``` on windows. 
I have added a link to the OpenSSL crate documentation that explains this.
> Add OpenSSL dependency in readme

- CHANGELOG.md
- README.md
- redirect_uri.html
- src/config.rs
- src/main.rs
- src/redirect_uri.rs
Based on feedback, some people found it confusing that the redirect URI landed you on local with non existent web server (basically a blank page).
It felt like something went wrong during setup.
This PR attempts to remove that confusion by displaying a very simple webpage, which will then get shutdown once auth is successful.
> Add a redirect_uri web server with basic webpage

- CHANGELOG.md
- src/handlers/input.rs
1. Fix "out-of-bounds" crash when pressing left too many times https://github.com/Rigellute/spotify-tui/issues/63
2. Fix issue that backspace always deleted the end of input, not where the cursor is https://github.com/Rigellute/spotify-tui/issues/33
> Fix input errors

- README.md
- src/app.rs
- src/handlers/artists.rs
- src/handlers/library.rs
- src/main.rs
- src/ui/mod.rs
This adds the basic implementation for an artists view. I have not added pagination, in my opinion it is better to do this in a future commit or PR.
I have chosen to present the result in a table and not in a list because I would like to show the saved songs by the user per artist like the Spotify desktop application does. When an artist is selected, the user will be shown all albums of an artist, this should probably be filtered in another commit or PR.
> Add artists view

- src/app.rs
- src/handlers/input.rs
- src/main.rs
Country is used by Spotify to determine which songs can be played by an user. By using the country from the users profile, the user does not have to configure it by themselves and the user will not be surprised when a song is not able to play because they have configured another country then in there Spotify account settings.
> Get country from user profile

- CHANGELOG.md
- src/app.rs
- src/handlers/home.rs
- src/ui/mod.rs
The CHANGELOG is included at build time and is scrollable after
selecting the "home" block.
Closes https://github.com/Rigellute/spotify-tui/issues/62
> Add CHANGELOG to home page

- CHANGELOG.md
- src/app.rs
- src/handlers/empty.rs
- src/handlers/mod.rs
- src/handlers/playbar.rs
- src/ui/mod.rs
When selecting the playbar, you can press `s` to save the currently
playing track. 
This opens up more possibilities such as viewing current playing track information.
> Make playbar selectable/hoverable

- CHANGELOG.md
- src/app.rs
- src/ui/mod.rs
This commit will show if the currently playing track is saved or not.
The idea here is to build a HashSet of saved track ids, to which UI components can simply look at to see if the track is saved or not.
As we fetch tracks around the app, we need to make an additional request to see if any are liked. 
So it should be pretty straightforward from here to add this to other views.
> Lay foundation for indicating if a track is saved

- src/main.rs
- src/redirect_uri.html
- src/redirect_uri.rs
This is my first approach of implementing https://github.com/Rigellute/spotify-tui/issues/96. The local webserver now starts just before the token request and listens for incoming GET requests. When a get request is received it tries to "parse" the URL. If the start of the webserver fails or the GET request cant be parsed it returns to manual authentication (old way).
The problem I see with the current state of my implementation:
- If the redirect url is not aimed at port 8888 but at a different port (since this can be configured in the Spotify Dashboard) the program would wait for ever because it won't receive a GET request. I guess I have to implement some kind of timeout after which the program will return to manual authentication.
What do you think?
> First implementation of automatic recognition of redirect url

- README.md
It's quite annoying that the compilation fails and you don't know about this upfront. Therefore I added generic information about the requirements.
> Add info about libssl and pkf-config requirement

- src/app.rs
- src/handlers/input.rs
- src/handlers/library.rs
- src/ui/mod.rs
All tables displaying songs are now marked with a heart (♥). Every time the track table is filled the liked_song_ids_set is populated with the liked songs. I also needed to make changes to how a table is represented to be able to ensure that the correct columns are formatted.
Track Table:
Album Table:
> Show heart next to saved songs 

- src/app.rs
- src/handlers/album_tracks.rs
- src/handlers/playbar.rs
- src/handlers/recently_played.rs
Pressing s now toggles the saved state of a song, which allows unsaving songs. Kept the old save_tracks despite it not being used for usage in future changes.
> Unsave already saved songs with 's'

- Cargo.lock
- Cargo.toml
- src/main.rs
This PR enables the output of the backtrace to the terminal when the app panics. This feature is currently only enabled in **Debug** and also ignores the `RUST_BACKTRACE` environment variable. It uses the workaround suggested here fdehau/tui-rs#177.
Unfortunately there is still an issue with the cursor placement after the crash where it is placed into the stacktrace output if the app was not run from the last line in terminal. Demonstration:
Cursor not at bottom before app is started:
Cursor at bottom before app is started (expected behaviour):
I couldn't figure out a solution yet but I think this could be fixed in a later PR because this is a valuable addition to track down the reason for crashes. This would improve situations like these …
> Show backtrace on app crash

- CHANGELOG.md
- src/app.rs
- src/handlers/album_tracks.rs
- src/main.rs
- src/ui/mod.rs
Toggle saving tracks did not work in the album tracks view. This change
also fixes displaying saved track status instantly.
> Fix save in album view

- README.md
- src/app.rs
- src/handlers/mod.rs
- src/main.rs
- src/user_config.rs
This will add a `config.yml` file along side the `client.yml` file which
will allow the user to configure custom keybindings.  Currently this
commit only covers global keybindings and not per-screen keybindings but
this could be added in the future. This commit also doesn't currently
allow for overriding default navigation keys (hjkl etc.) but that could
also be added later.
Resolves: #46
> Add keybinding config file

- src/app.rs
Addresses https://github.com/Rigellute/spotify-tui/issues/123.
Not sure if there is an edge case to be concerned about:
If the user is at the end of a track and attempts to seek forward twice quickly (between ticks), it may be possible that `self.next_track` is called twice and playback unexpectedly skips forward two tracks instead of the one as expected.
Am open to suggestions for better alternatives.
> Fix panic when seeking beyond track boundaries

- src/ui/mod.rs
This should not happen now due to the fixes in PR #124. However this is
an extra precaution in case tracks can have negative progress due to
some other bug in the future.
Closes #125 issue
> Prevent Gauge error when track progress is negative

- src/app.rs
- src/handlers/album_list.rs
- src/handlers/library.rs
This PR is related to #11
`ctrl+d/u` should scroll through pages but this has been implemented in "Liked Songs" view only. In this PR, I tried to implement scrolling down/up in the "Albums" view.
need to confirm:
In `src/app.rs`, I added three methods (`get_current_user_saved_albums`, `get_current_user_saved_albums_next`, and `get_current_user_saved_albums_previous`) for `App`. These methods are imitation of `**saved_tracks**` methods. Although `push_navigation_stack` is called in `get_current_user_saved_tracks`, I did **NOT** call `push_navigation_stack` in `get_current_user_saved_albums`.  If `push_navigation_stack` is called after each page scrolling, same contents are pushed into the stack. Scrolling pages several time, q key (go back) seems foul-up. This behavior seems a bug for me …
> Add support for scrolling up/down when album list is active

- src/handlers/artist_albums.rs
Addresses https://github.com/Rigellute/spotify-tui/issues/106
> fix: display correct artist album track listing

- src/app.rs
- src/handlers/library.rs
- src/handlers/playlist.rs
- src/handlers/search_results.rs
- src/handlers/track_table.rs
Reverts Rigellute/spotify-tui#133
One issue I found was that pressing "enter" to play a track, would play a track from the wrong page (I think it's only playing tracks from the first page?)
> Revert "Add support for page scrolling in Playlist"

- src/ui/mod.rs
First crack at addressing https://github.com/Rigellute/spotify-tui/issues/10.
Since tui-rs' `Table` widget does not automatically scroll to the seleted item automatically, I took some inspiration from the [`SelectableList` widget](https://github.com/fdehau/tui-rs/blob/master/src/widgets/list.rs#L213-L239) which does.
> 10 scroll to selected item

- src/ui/mod.rs
- src/ui/util.rs
Occasionally the track percentage goes out of bounds (0 & 100). There's
probably a more elegant fix for this, but this seems fine for now.
> Fix gauge error

- src/app.rs
There was a race condition between selecting a new track and the track
progress updating; this caused the app to sometimes panic when
selecting a track which has a total duration less than the current
progress as it tries to report a negative remaining time in the playbar
(but it tries this with unsigned values).
```bash
/git/spot.. master λ › cargo run
Compiling spotify-tui v0.8.0 (/home/user/git/spotify-tui)
Finished dev [unoptimized + debuginfo] target(s) in 6.75s
Running `target/debug/spt`
thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/ui/util.rs:52:39
stack backtrace:
...
6: core::panicking::panic
at src/libcore/panicking.rs:49
7: spt::ui::util::display_track_progress
at src/ui/util.rs:52
8: spt::ui::draw_playbar
at src/ui/mod.rs:685
9: …
```
> fix: Update current progress at new track load

- src/ui/mod.rs
This commit closes #138
There will still be some padding on larger terminals but I've removed the padding when the height is small.
Also slightly reduced the amount of margin on larger terminals.
> Use space more efficiently on small terminals

- src/app.rs
- src/handlers/library.rs
Go back `q` does not work as expected after scrolling pages in Liked Songs.
When i scrolled pages in Liked Songs and pushed `q`, i expected that the Library block is activated but nothing occurred.
This problem caused by calling push_navigation_stack in get_current_user_saved_tracks.
I tried to fix this problem by removing push_navigation_stack from get_current_user_saved_tracks and pushing to the stack is called first time.
> Go back does not work in Liked Songs

- src/main.rs
When terminal size is changed, some contents are not showed in the table. Additionally, regardless terminal size, search returns only 4 contents.
Here, I tried to fix these problem, i adjust search limits depending on the terminal size. However, parameters I used here are not led deductively but empirically.
If you know the way to get height of each block, preferable implementation can be available. For me, my implementation is not smart and if you have any idea, please tell me it.
> Adjust search limits

- src/app.rs
- src/handlers/playlist.rs
- src/handlers/track_table.rs
Added some simple pagnation to at least scroll through your playlist. I don't know if this is the best way to implement it but it seems to work fine from my own testing. Please excuse if my Rust is "rusty", it's my first Rust project and I don't know if there is need for memory optimization for this change to not leak memory.
> Added pagnation to user playlists

- src/app.rs
- src/handlers/album_list.rs
In the roadmap, delete saved contents is essential but it is not implemented yet.
Here, I tried to implement delete saved album and it seems to work well.
I assigned `D` to delete an album in album list but i do not know this key mapping is good for you and if you do not like this, please change key mapping.
> Delete saved album

- Cargo.lock
- Cargo.toml
- README.md
- src/app.rs
- src/handlers/mod.rs
- src/main.rs
- src/ui/help.rs
- src/user_config.rs
Hey, 
first of all: Awesome project! 
I implemented a new feature that copies the url of the currently playing track when you press a button (`c` by default). 
This is my first time using rust, so if you find any mistakes or weirdness, let me know and I will fix the issues. 
I hope I found all the relevant sections I needed to adjust.
> add hotkey to copy url of currently playing track

- Cargo.lock
The app would hang upon trying to authenticate with Spotify
on FreeBSD, bumping the versions to the latest seems to have
fixed this issue. All tests pass and works as expected.
> Bump versions in Cargo.lock.

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- README.md
- src/app.rs
- src/handlers/mod.rs
- src/main.rs
- src/ui/help.rs
- src/user_config.rs
Original PR here https://github.com/Rigellute/spotify-tui/pull/156
This PR attempts to fix CI/CD by installing the `xorg-dev` dependency.
> Lenny penny clipboard

- src/main.rs
I found a small mistake in my past PR #154.
I used `max` to get the maximum search limit but it cause an error depending on terminal size because of a rule provided by spotify api.
Here, i use `min` instead of `max` and the error does not occur.
> Use min instead of max

- src/ui/mod.rs
Massive PR! 😄 
The `Release Date` column was missing in the `Albums` table, which was caused by width exceeding the total available space.
The same happens for `Length` in `Recently Played Tracks` table, because of `Liked` column of fixed width `2`. I couldn't decide whether change it to a percentage calculated value or just subtract it from the next column (eg. `width: get_percentage_width(layout_chunk.width, 2.0 / 5.0) - 2`). What do you think @Rigellute ? 
| Before               | After               |
| -------------------- | ------------------- |
| <img width="600" alt="Screenshot 2019-11-24 at 21 16 03" src="https://user-images.githubusercontent.com/6296883/69502004-61009200-0f02-11ea-86da-33d964db7d6d.png"> | <img width="600" alt="Screenshot 2019-11-24 at 21 15 32" …
> Fix columns width in Saved Albums

- src/ui/mod.rs
The `Length` column was missing in the `Recently Played Tracks` table, which was caused by width exceeding the total available space.
| Before               | After               |
| -------------------- | ------------------- |
| <img width="500" alt="Screenshot 2019-11-25 at 09 55 21" src="https://user-images.githubusercontent.com/6296883/69530634-43671300-0f6a-11ea-972a-d77826e51b16.png"> | <img width="500" alt="Screenshot 2019-11-25 at 09 54 49" src="https://user-images.githubusercontent.com/6296883/69530579-29c5cb80-0f6a-11ea-85e6-774b5ea6d9be.png"> |
> Fix columns width in Recently Played Tracks

- src/ui/mod.rs
Previously, the text of AlbumTrack was set to "AlbumText", when it should be simply "Album".
> Small typo fix for AlbumTrack header

- src/app.rs
The volume control does not work as intended, if `+` and `-` are pressed in a moderate pace the value updates every second press, and after some time it starts to get even more messy.
I have removed `get_current_playback` call after the successful volume change. In this context I think it is not necessary to poll for the playback data, but maybe I am missing something, would you be able to confirm it @Rigellute ?
| Before               | After               |
| -------------------- | ------------------- |
| ![bbb](https://user-images.githubusercontent.com/6296883/69582912-89a38d00-0fd1-11ea-9347-ddbe4863396e.gif) | ![aaa](https://user-images.githubusercontent.com/6296883/69582881-755f9000-0fd1-11ea-8288-282b3e261bbf.gif) |
> Adjust volume controls behaviour

- src/app.rs
Currently if the initial volume is not of full tens (eg. `42`) then the min and max values are respectively `2` and `92`.
Limit the volume values correctly on `0` and `100`.
| Before               | After               |
| -------------------- | ------------------- |
| ![v2](https://user-images.githubusercontent.com/6296883/69675197-0009c300-1096-11ea-953c-f6114aa1b196.gif) | ![v1](https://user-images.githubusercontent.com/6296883/69675211-0c8e1b80-1096-11ea-84d4-9c09c9a46f8d.gif) |
> Adjust min/max volume values

- src/handlers/search_results.rs
After scroll page in a playlist in my playlists, an wrong track is played when i tried to play a track in a playlist in search results. 
Here, I reset `app.playlist_offset` to zero when a playlist is selected in search results to fix this behavior.
> Fix playing a wrong track in playlist

- src/app.rs
- src/handlers/album_list.rs
- src/handlers/playlist.rs
- src/handlers/search_results.rs
- src/main.rs
here, i implement `current_user_saved_album_add`, `follow_user_playlist`, and `follow_user_playlist`. I think that add/follow and delete/unfollow are implemented in all contents. If there are oversights, tell me them.
> Add support for adding an album and following a playlist

- README.md
- src/app.rs
- src/user_config.rs
This adds the config value `seek_seconds` to change much `spotify-tui` seeks when pressing the seek hotkeys. 
Default is still `5000` ms.
> make seeking amount configurable

- src/handlers/track_table.rs
- src/ui/help.rs
Hello,
Here's a patch to allow a user to jump to the end / start of a playlist.
I used the same shortcut as the one used to go at the end / start of the search input but I'm not sure if you are ok with that. If you are, I guess we'd have to find how to specify it in the help page.
I also didn't implement it for other variants of `TrackTableContext` as I'm not sure if that's worth it.
Let me know how you feel about this and thanks for your work on this client :)
> Playlist: add shortcuts to jump to the start or the end

- src/handlers/input.rs
After searching, playlist index is changed to `None` and it makes playlist selection odd.
I deleted a line that binds `None` to `selected_playlist_index` and it worked well.
> Fix playlist index after search

- src/main.rs
- src/ui/mod.rs
On smaller height terminals, the cursor position was off.
Fix is to apply the same offset differences on small/large terminals as is applied to the margin.
This commit closes https://github.com/Rigellute/spotify-tui/issues/175
> 175: Fix cursor offset in search input

- src/main.rs
This is fixing #174 
First of all I wanted to say that I'm pretty new to Rust so if you notice anything and have tips for me please feel free to share them with me :)
Also I realized that if the first action is to use the input field (thus the second route in the `navigation_stack` being a route with the id `Search`) the `Home` route will not be shown on navigating back because the second route will be popped in the match I've added and the `is_none()` check will break after...
I didn't know how to prevent this effectively without slaughtering the code. So any ideas would be really appreciated.
> Remove focus on input when jumping back

- src/ui/mod.rs
Currently there are different-length strings for parameters, such as
`On` and `Off`. When you switch options, the bottom status bar
reformats. This is a worse user experience, so this diff pads the bottom
status line so that it never reformats.
The included gifs show the end result.
> Pad strings in status bar to prevent reformatting

- src/app.rs
- src/handlers/artist.rs
- src/handlers/artists.rs
- src/handlers/common_key_events.rs
- src/handlers/empty.rs
- src/handlers/mod.rs
- src/handlers/search_results.rs
- src/ui/mod.rs
- src/ui/util.rs
- src/util.rs
Selecting an artist in artists or search result view show the artist's album so far. In this PR, I modifed to show top tracks and related artists of the selected artist.
Before:
After:
> Add support for Related artists and top tacks

- src/main.rs
A failure can happen if spt is run in an environment that doesn't have
access to an xorg server.
Closes #195
> Don't error if failed to open clipboard

- src/app.rs
This PR mimics the behavior of the previous button in the official client by only going to the previous track if current track time is under three seconds.
Alternative to #215 
Closes #214
> Make behavior of previous button mimic behavior in official Spotify client

- src/app.rs
- src/handlers/track_table.rs
Addresses #192. 
Previously, when using CTRL+d to page downwards on a playlist, there was no guard against incrementing the playlist offset past the end of the playlist, resulting in empty track tables. This commit checks if the track table is empty after attempting a CTRL+d scroll and backtracks to
the previous playlist offset.
From what I can tell, the Spotify API doesn't offer a way to get the total size of a playlist, so we can't just check before making a request whether we're about to scroll past the end (which would be ideal). This means that hitting CTRL+d at the end of a playlist results in two API requests (one to notice we got an empty response, and another to reload with the old limit), and consequently this implementation is a bit on the slow side.
I'm quite new to Rust, so …
> Disallow CTRL+d scroll past playlist end

- Cargo.toml
- src/app.rs
- src/handlers/album_tracks.rs
- src/handlers/artist.rs
- src/handlers/artists.rs
- src/handlers/common_key_events.rs
- src/handlers/recently_played.rs
- src/handlers/search_results.rs
- src/handlers/track_table.rs
- src/ui/help.rs
- src/ui/mod.rs
I implemented a feature which on keypress 'r' loads a list of recommended songs for the selected song or artist and starts playback. This functionality was requested in issue #171 (see also #129).
> Add play recommendations for song/artist on pressing 'r'

- .github/workflows/cd.yml
As per #69, here's a PR that adds windows to the CD build matrix.
Making it work was surprisingly simple since almost everything used is the same across platforms (yay, rust ecosystem!) 
Here's a sample release: https://github.com/MCOfficer/spotify-tui/releases/tag/v0.0.3
> Add Windows CD

- src/handlers/artists.rs
- src/ui/help.rs
Hi there,
My first PR to address #213.
I added the ability to play every song for an artist from `artists`, I think it corresponds to the `Artists` tab from `Library`. I did it according to @Rigellute indications.
I am not sure if it should be implemented in another place.
Don't hesitate if you have any comments!
> Play every known song with e

- README.md
- src/app.rs
- src/event/events.rs
- src/handlers/analysis.rs
- src/handlers/common_key_events.rs
- src/handlers/mod.rs
- src/main.rs
- src/ui/audio_analysis.rs
- src/ui/help.rs
- src/ui/mod.rs
- src/user_config.rs
The spotify API has a [audio analysis endpoint](https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis/) for a given track.
This is an experimental attempt to use that data to "visualise" a track using a bar chart.
This is very basic but the visualisation is based on the "pitch" information for a given "section" of the piece. To make things more animated, in between the section data I create an offset and subtract from the pitch information based on the current beat.
You can now also configure the `tick_rate` of the app. The lower this number the smoother the animations are. But this comes at a cost of higher CPU usage!
> Experimental audio visualiser

- README.md
Thanks to contibutions by @popey, @AivreeG, and @hurricanehrndz, we can install `spt` with `snap`.
However, the instruction written in `README` is not updated.
Here, I updated the instruction to install stable version of `spt` with `snap` and add a new instruction to install nightly build of it.
> Modify instruction to install with snap

- src/app.rs
- src/handlers/help_menu.rs
- src/main.rs
- src/ui/mod.rs
Fixed issue #301 by adding the ability to split the help menu into pages. The help menu can be navigated in a similar manner to the track list (Ctrl+D and Ctrl+U).
> Add pagination to the help menu

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/handlers/album_list.rs
- src/handlers/album_tracks.rs
- src/handlers/artist.rs
- src/handlers/artists.rs
- src/handlers/empty.rs
- src/handlers/home.rs
- src/handlers/input.rs
- src/handlers/library.rs
- src/handlers/made_for_you.rs
- src/handlers/mod.rs
- src/handlers/playbar.rs
- src/handlers/playlist.rs
- src/handlers/recently_played.rs
- src/handlers/search_results.rs
- src/handlers/select_device.rs
- src/handlers/track_table.rs
- src/main.rs
- src/network.rs
- src/redirect_uri.rs
- src/ui/mod.rs
- src/ui/util.rs
- src/user_config.rs
This is a huge PR that changes the architecture of the app considerably.
The idea is to create thread that will handle network events, while the main thread will handle the UI rendering loop.
The implication of this change is that the UI thread will disptach (or send) messages to the network thread for it then to execute the async action.
Thus, slow network calls will no longer block the UI thread meaning the app should feel more responsive on slow connections.
I have tested on very slow internet connections and can see these changes will drastically improve both #92 and #207. 
Given the scale of these changes, I encourage anyone to checkout this branch and test!
> Create a thread for network events

- src/app.rs
- src/handlers/basic_view.rs
- src/handlers/common_key_events.rs
- src/handlers/mod.rs
- src/main.rs
- src/ui/mod.rs
- src/user_config.rs
Pressing `B` will take you to a "basic view", which is just a centered
playbar.
Closes #320
> Add basic view

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/config.rs
- src/main.rs
- src/network.rs
- src/user_config.rs
Unlike failure, anyhow is built around the standard library's std::error::Error trait rather than a separate trait failure::Fail. The standard library has adopted the necessary improvements for this to be possible as part of RFC 2504.
I plan to replace failure in rpsotify too.
> Replace failure with anyhow

- src/handlers/artists.rs
Simple check for an out of bounds panic.
I don't really use Spotify, but I was curious to try your application, so after creating new account I've encountered this segfault.
> Fix crash when there're no artists avaliable

- src/app.rs
- src/handlers/search_results.rs
**How to reproduce the problem:**
1) Follow any playlist, it will appear in the left frame "Playlists"
2) Search for any other playlist and select it in the corresponding frame
3) Press 'D'
The one that you were following will disappear. 
A simpler case - have no playlists followed and press 'D' - the application will panic with an out of bounds.
Unfollowing playlists from search results should be handled separately.
> Correctly handle playlist unfollowing

- src/app.rs
- src/main.rs
- src/network.rs
When using the cached Spotify token, the expiration time was not correctly computed. As a consequence, the re-authentication was not triggered.
I had to move from `Instant` to `SystemTime`. I hope this is OK.
Closes #410
> Fix token expiration time

- Cargo.lock
- Cargo.toml
- src/ui/audio_analysis.rs
The Spotify endpoint for audio analysis has recently changed - some fields are now undefined. 
There is no official documentation of this, which is why I've had to use the heavy handed approach of making all
audio analysis properties optional (fix made in [rspotify](https://github.com/ramsayleung/rspotify/pull/94)).
This fix won't be accepted upstream (see link above), so I've had to use my fork of rspotify to fix this in the meantime.
Hopefully a more permanent fix will follow.
Closes #416
> Temp fix audio_analysis feature

- src/ui/help.rs
> moved pagination to start of help-file

- README.md
- src/ui/mod.rs
- src/user_config.rs
This new setting, `show_loading_indicator`, can be added to the behavior section
of the user configuration. Defaults to `true` to maintain existing behavior of
showing the loading indicator. Set to `false` to disable the loading indicator.
[Resolves #420]
> Add user configuration toggle for the loading indicator

- Cargo.lock
- Cargo.toml
This dep is not explicitly used in the source code and was added a while back to resolve a dependancy version locking issue. 
This seems to not be the case anymore though, so I'm removing it.
> Remove proc-macro2

- Cargo.lock
- Cargo.toml
- src/ui/audio_analysis.rs
The Spotify API has fixed the audio analysis endpoint on their end, so
my fork of rspotify is no longer needed.
Closes #437
> Use upstream rspotify

- README.md
Hi @Rigellute, thanks a lot for creating this. I was tweaking my colour configuration and wanted to make it easier to know which colours are used where. I added comments for each colour except `playbar_text` — I kept changing it, but couldn't notice a difference. Maybe it's not being read properly?
> add comments explaining user-configurable colours

- src/handlers/album_tracks.rs
Adds a new feature to add to saved albums when pressing 'w' key on album view.
closes #444 
Any comments or suggestions are welcome.
> Feature: Add save album on album view

- src/handlers/input.rs
> Enable Unix and Linux shortcut keys in the input.

- src/ui/mod.rs
This is shown in the Simplified context, but wasn't in the Full context.
This causes the undesired behavior that getting to an album from the
library context has a missing field (see #488).
Fixes #488
> Add album artist field to full album view

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/handlers/basic_view.rs
- src/handlers/mod.rs
- src/handlers/playbar.rs
- src/handlers/search_results.rs
- src/handlers/track_table.rs
- src/network.rs
- src/ui/mod.rs
The latest version of [`rspotify`](https://github.com/ramsayleung/rspotify/blob/master/CHANGELOG.md#010-20200701) brings support for podcasts! 
spotify-tui itself still needs to implement searching and playing podcasts, but this PR will enable its development.
This upgrade introduced a number of breaking changes, but thanks to the amazing type system and the Rust compiler, it was fairly easy to just follow the errors for everything to Just Work!
> Upgrade rspotify to 0.10.0 (Podcast support)

- README.md
`spotify-tui` has been in the stable channel for Nix/NixOS for some time now. Would be a really good addition to the installation section as the Nix package manager can be used on MacOS and virtually any linux distro.
> Document Nix support

- src/ui/help.rs
I wanted to save an album to my library as I am used to, but the current help lines didn't make it clear enough that it was even possible from a search result. After trawling through PRs, I found #506, which does exactly what I was looking for, but that change wasn't accompanied by a change in the UIs help section.
I also fixed a small typo where the sentence didn't read properly when plural was used for "artist".
> Add additional line of help to show that 'w' can be used to save/like an album

- src/handlers/input.rs
> Add handling Home and End buttons in user input

- Cargo.lock
- Cargo.toml
- src/ui/audio_analysis.rs
- src/ui/mod.rs
- src/user_config.rs
This is from issue #490 
There doesn't seem to be support for changing the color of the text when the bar is overlapping to anything else though. This is hardcoded into tui to use the background of the gauge...
> Issue #490 updated tui to 0.10.0 and added playbar_progress_text option

- README.md
- src/ui/mod.rs
- src/user_config.rs
As mentioned in Issue #568, some users' terminals can have escaping issues with text emphasis.
This pull request introduces a new field named `enable_text_emphasis` to `BehaviorConfig`.
`BehaviorConfig` seemed better suited as a home for this bit than `Theme`, and required less work. ;-)
Open to simpler/more sustainable ways to make this change, of course! First time contributer here.
> Add 'enable_text_emphasis' behavior config option

- src/app.rs
Before this commit, if a user pressed `v` multiple times, they would
have to press `q` the same number of times to get to the previous view.
This commit makes it so that an analysis view entry is only pushed into
the navigation stack if the current view isn't an analysis one.
> Don't add analysis view to stack if already in it.

- src/handlers/album_list.rs
- src/handlers/home.rs
- src/handlers/track_table.rs
- src/user_config.rs
resolves #482 
@AndydeCleyre, @vidurb might want to know
This allows the 4 keybinds to be bound to something else (something that doesn't colide with people's tmux keybinds and such)
> Add next/prev page, jump to start/end to user config

- README.md
spotify-tui is available as an official tap
Trying to install with the current instructions gives an error
`Error: No available formula or cask with the name "Rigellute/tap/spotify-tui"`
> Updated README with correct brew command

- README.md
- src/ui/mod.rs
- src/user_config.rs
- Header text in panes is not affected by the color value set for 'text' in config.yml
- Results in headers always written in white, which causes clash with non-white themes
- Add new theme 'header' setting and use it to style the header text
> Add user-configurable header styling

- src/app.rs
- src/handlers/artists.rs
- src/network.rs
This closes #603 which I just filed.
I'm new to Rust, so any feedback is welcome!
Lastly, I think pagination behavior may be in want of a re-work. It seems like we're missing pagination for a bunch of views and I imagine their implementations will all share quite a bit in common. I didn't take on the larger task of a big refactor but it may be something we should consider.
Here's a demo gif (ignore color issues, it's my first time trying to use `terminalizer` to record my terminal).
> Implement next/previous page behavior for the Artists table

- src/network.rs
This closes #611 which I just filed.
Check out the issue for some screenshots. This PR effectively makes the second screenshot in that issue description correct, in that it recognizes the saved albums on that artist.
As mentioned in that issue too, we seemingly _do not_ update the saved tracks set when searching, so I omitted adding that into this patch, but it's easy enough to extend this patch to apply to tracks and make things consistent.
> Update the saved albums cache set when getting an artist

- src/ui/mod.rs
- src/ui/util.rs
`draw_input_and_help_box` moved to `draw_user_block` so the search and help bar is reduced and the main panel is adjusted to fill that space. The constraints of size of both functions were tweaked as well to better fit the new layout. 
I feel this new layout does a better job at taking advantage of space as the strings we search are usually not that long and after some use of the client the help bar becomes more or less irrelevant. 
Here some screenshots 
Fullscreen in a 1080p monitor 
Halfscreen in a 1080p monitor 
Current layout for comparison
> Simple change of layout 

- src/handlers/input.rs
- src/network.rs
- src/ui/mod.rs
This closes #41.
To be more precise, this actually adds significantly more functionality than what is requested in #41. In particular, this PR adds support for opening:
- Tracks (will open its containing album and move the selection to the searched track)
- Albums
- Artists
- Playlists
- Shows/Podcasts
Via either their Spotify share URL, e.g.:
```
https://open.spotify.com/album/6QdCohkHKNTVoaSx1ZzitH?si=vJQhe4H5RwiGcDf4xr9DuQ
```
Or their Spotify URI:
```
spotify:album:6QdCohkHKNTVoaSx1ZzitH
```
On the official desktop client, searching with either of these leads you to the Metallica album, [Metallica](https://open.spotify.com/album/6QdCohkHKNTVoaSx1ZzitH).
If the given input string fails to match either URI format, it will default to the original raw phrase search.
Here are some …
> Support searching by Spotify share URLs and URIs analogously to the desktop client

- src/app.rs
- src/network.rs
- src/ui/mod.rs
Instead of immediately sending the API request when '<' or '>' is
pressed, the offsets are accummulated. The seek request is sent
periodically along with the playback update request.
Also, the progress bar in the UI shows the desired seek position even
before the actual seek is performed.
> Optimize seek (#523)

- README.md
- src/ui/mod.rs
- src/user_config.rs
This closes #625.
Sorry this took longer than it should have. I got distracted.
Anyways, it's a pretty simple change. I only have one reservation about the naming.
Here's a screenshot of it in action:
And here's the accompanying config:
```yaml
theme:
...
behavior:
liked_icon: "★"
```
> Make the liked icon configurable

- src/ui/mod.rs
- src/ui/util.rs
This commit improves the centering of the basic_view_widget and thus
fixeds the issue #508 by manually calculating the space between the top
and the bottom bezel of the terminal. Improved version of #509.
> Fix issue #508 by calculating space manually

- README.md
I noticed that the `Create a Client ID` button doesn't exist anymore in the [Spotify dashboard](https://developer.spotify.com/dashboard/applications), so I updated the instructions accordingly.
> Updated Spotify API connection instructions

- src/app.rs
- src/handlers/empty.rs
- src/handlers/library.rs
- src/handlers/podcasts.rs
- src/handlers/search_results.rs
- src/network.rs
- src/ui/mod.rs
Implemented:
- Podcasts page shows list of user's saved podcasts (columns: name, publisher(s))
- Pressing "Enter" on podcast goes to episode table
- Pressing "D" unsaves selected podcast
Functions related to podcasts that are not yet implemented:
- ~~Showing heart next to followed podcasts in search results~~
- ~~Ability do follow/unfollow from search results~~
- Ability to follow/unfollow from episode table
Possible additions:
- Add name of podcast to episode table
I'm willing to work on these other functionalities too but I thought it would be good to get feedback for what I have already done. 
And I was wondering if it was okay to add a `selected_show_id` field to `App`, because to implement following/unfollowing from the episode table we need the viewed show's id. Another way would be …
> Implement Podcasts Library page

- src/app.rs
A small fix that changes the url to the currently playing album from `https://open.spotify.com/album/{track.id}`
to `https://open.spotify.com/album/{track.album.id}`. The old url didn't open for me, the new does.
> Fix url to share the current album/show

- Cargo.lock
- Cargo.toml
- src/app.rs
Replaces the unmaintained `clipboard` with [`arboard`](https://github.com/ArturKovacs/arboard)
> Replace `clipboard` with `arboard`

- src/cli/clap.rs
- src/cli/cli_app.rs
- src/cli/handle.rs
- src/cli/util.rs
- Add new `--seek` to jump forward, backwards
- Add new `%r` to the format options to display the current progress
- Add a longer help to the `--seek` option
For example: `spt pb --seek +10` jumps ten second forwards, `spt pb --seek -10` ten seconds backwards and
`spt pb --seek 10` to the tenth second of the track.
> Add ability to seek from the CLI

- src/config.rs
* Asks user for Client ID/Secret until a valid input is entered (32 hex digits)
This makes it such that the config file is not written unless valid inputs are entered, so the user will not have to manually edit or delete the config file.
> Handle invalid Client ID/Secret

- src/cli/clap.rs
- src/cli/cli_app.rs
- src/cli/util.rs
Title. After some usage I feel that this makes more sense. Related to this issue: #429, idea from @spenat28.
> Change `--like` that toggles the state to explicit `--like` and `--dislike` flags

- README.md
Recent versions of Cargo check for updates when using `install` and no longer require `--force`. See [this page of the Cargo Book](https://doc.rust-lang.org/cargo/commands/cargo-install.html):
> If the package is already installed, Cargo will reinstall it if the installed version does not appear to be up-to-date. If any of the following values change, then Cargo will reinstall the package: [...]
> README: change update instructions

- README.md
- src/ui/mod.rs
- src/user_config.rs
This adds an option with the name `behavior.enforce_wide_search_bar` to make the search bar wider. Fix for #737
> `enforce_wide_search_bar` to make search bar bigger

- src/user_config.rs
Previously, text would be white, which is not visible on bright color
schemes. The color for non-highlighted text now uses the default
foreground color of the users terminal emulator, making it visible in
any theme. The only visual change in dark color schemes is that the
playbar text might go from black to white, depending on the users
terminal emulator (some terminal emulators swap fore- and background
colors on a colored background depending on the background color; this
is IMO the correct behavior anyway).
> Replace black and white default colors with reset.

- src/network.rs
This change should resolve the issue with users being rate limited when leaving spotify-tui running without anything playing. This should solve #779 .
> Fixed rate limiting issue

- src/app.rs
Hi guys 👋,
First attempt at a PR here and attempted to resolve [issue](https://github.com/Rigellute/spotify-tui/issues/821)
Did this by `dedup`ing any routes on the navigation stack with matching ids.
---
The device selector popup can be opened multiple times by pressing `d` more than once.
To get back to the main menu, each of these needs to be closed separately by pressing `q` the same number of times.
It would be nicer if pressing `q` only once always goes back to the main menu.
E.g, actual behavior:
press `d`
press `d`
press `q`
You're seeing the device selector
expected behavior:
press `d`
press `d`
press `q`
You're seeing the main menu
> Pressing `d` twice requires `q` twice to exit

- README.md
- src/main.rs
- src/user_config.rs
This adds an option to set the window title to "Spotify TUI" on startup. 
This is very handy when switching windows via something like dmenu, since it makes the terminal window where spotify-tui is running easy to find. 
There are a few choices that I wasn't sure about though:
- I've added the configuration option under "behavior", is there a better place for it? 
- I've set it to enabled by default, since it's a very well supported xterm feature so it shouldn't cause problems for most people. Should it default to false to maintain existing behavior on upgrade?
- Since the binary is called spt, i've set the title to "spt - Spotify TUI", in case people want to locate the window by the name of the command they used to start the application. But just "Spotify TUI" is probably nicer and maybe …
> Add option to set window title to "spt - Spotify TUI" on startup
